import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import { Icon } from '@iconify/react';
import "./globals.css";
import { Navbar } from "./Navbar";

const cabin = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cabin.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}


